name: fetch_api
description: JavaScript bindings for Fetch API, flexible HTTP requests, redirects, streaming and more.
version: 2.2.1
homepage: https://github.com/Zekfad/fetch_api
repository: https://github.com/Zekfad/fetch_api
issue_tracker: https://github.com/Zekfad/fetch_api/issues
# documentation: https://pub.dev/documentation/fetch_api/latest/
topics:
  - web
  - fetch

platforms:
  web:

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  # no upper bound, because we use only Types
  web: '>=0.5.0'

dev_dependencies:
  build_runner: '>=2.4.8'
  build_web_compilers: '>=4.0.9'
  zekfad_lints: ^2.0.0
